#!/usr/bin/env python

# Copyright 2018 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# hyperparam.yaml
trainingInput:
  scaleTier: CUSTOM
  masterType: complex_model_l
  workerType: complex_model_l
  workerCount: 1
  hyperparameters:
    goal: MAXIMIZE
    maxTrials: 10
    maxParallelTrials: 1
    hyperparameterMetricTag: my_metric_tag
    enableTrialEarlyStopping: TRUE 
    params:
    - parameterName: max_depth
      type: INTEGER
      minValue: 8
      maxValue: 11
    - parameterName: n_estimators
      type: INTEGER
      minValue: 500
      maxValue: 1500
    - parameterName: learning_rate
      type: DOUBLE
      minValue: 0.03
      maxValue: 0.5
    - parameterName: booster
      type: CATEGORICAL
      categoricalValues: [
          "gbtree"]
    - parameterName: bin_or_numerical_class
      type: CATEGORICAL
      categoricalValues: [
          "numerical","binary"]
    - parameterName: extract_times
      type: CATEGORICAL
      categoricalValues: [
          "true","false"]

#to resume job
#trainingInput:extract_times
#  hyperparameters:
#    #goal: MAXIMIZE
#    maxTrials: 2
#    maxParallelTrials: 2
#    resumePreviousJobId: fraud_detection_hp_tuning_20190918_132014
